name: trans
version: 1.0.2+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cloud_firestore: any
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  gap: ^3.0.1
  get: 4.6.6
  google_fonts: ^6.1.0
  http: any
  image_picker: 1.0.7
  intl: ^0.19.0
  quickalert: ^1.0.2
  shimmer: ^3.0.0
  slide_to_act: ^2.0.2
  sliding_up_panel: ^2.0.0+1
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

